### ISSUE TITLE
Duplicate mapping key and parsing error when trying to add a map entry

### ISSUE THREAD

**Issue by chriskelly** [dart-lang/yaml_edit#69]
I'm trying to add a key to a map and set its value, but running into issues.

```yaml
# Input Yaml
- name: foo
  id: "A"
- name: bar

# Desired output Yaml
- name: foo
  id: "A"
- name: bar
  id: "B"
```

Example code for Duplicate mapping key error
```dart
import 'package:yaml_edit/yaml_edit.dart';

void main() {
  const yaml = '''
- name: foo
  id: "A"
- name: bar
  ''';
  final yamlEditor = YamlEditor(yaml);
  yamlEditor.update(
    [1, 'id' ],
    "B",
  );
  print(yamlEditor);
}
```

For this, I get the following error:
```bash
Unhandled exception:
Error on line 3, column 3: Duplicate mapping key.
  ╷
3 │   id: B
  │   ^^
  ╵
#0      Loader._loadMapping (package:yaml/src/loader.dart:171:9)
#1      Loader._loadNode (package:yaml/src/loader.dart:92:16)
#2      Loader._loadSequence (package:yaml/src/loader.dart:146:20)
#3      Loader._loadNode (package:yaml/src/loader.dart:90:16)
#4      Loader._loadDocument (package:yaml/src/loader.dart:68:20)
#5      Loader.load (package:yaml/src/loader.dart:60:20)
#6      loadYamlDocument (package:yaml/yaml.dart:72:25)
#7      loadYamlNode (package:yaml/yaml.dart:57:5)
#8      YamlEditor._performEdit (package:yaml_edit/src/editor.dart:576:24)
#9      YamlEditor.update (package:yaml_edit/src/editor.dart:271:14)
#10     main (package:yaml_playground/example.dart:11:14)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

If I swap the order around and try to update the first list item instead, I get a different error
```dart
import 'package:yaml_edit/yaml_edit.dart';

void main() {
  const yaml = '''
- name: foo
- name: bar
  id: "B"
  ''';
  final yamlEditor = YamlEditor(yaml);
  yamlEditor.update(
    [0, 'id' ],
    "A",
  );
  print(yamlEditor);
}
```
```bash
Unhandled exception:
Error on line 2, column 1: Only expected one document.
  ╷
2 │ ┌ - name: foo
3 │ │ - name: bar
4 │ │   id: "B"
5 │ └   
  ╵
#0      loadYamlDocument (package:yaml/yaml.dart:80:5)
#1      loadYamlNode (package:yaml/yaml.dart:57:5)
#2      YamlEditor._performEdit (package:yaml_edit/src/editor.dart:576:24)
#3      YamlEditor.update (package:yaml_edit/src/editor.dart:271:14)
#4      main (package:yaml_playground/example.dart:11:14)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

In a larger example that I can't duplicate in this smaller example, the error I get in this case is: `Expected a key while parsing a block mapping.`

Using version yaml_edit: ^2.2.0

**Comment by chriskelly** [comment]
And here's an even weirder error if neither map has the 'id' key

```dart
import 'package:yaml_edit/yaml_edit.dart';

void main() {
  const yaml = '''
- name: foo
- name: bar
  ''';
  final yamlEditor = YamlEditor(yaml);
  yamlEditor.update(
    [
      1,
      'id',
    ],
    "B",
  );
  print(yamlEditor);
}
```
```bash
Unhandled exception:
Assertion failed: (package:yaml_edit) Modification did not result in expected result.

# YAML before edit:
> - name: foo
> - name: bar
>   

# YAML after edit:
> - name: foo
>   id: B
> - name: bar
>   

Please file an issue at:
https://github.com/dart-lang/yaml_edit/issues/new?labels=bug

#0      YamlEditor._performEdit (package:yaml_edit/src/editor.dart:578:7)
#1      YamlEditor.update (package:yaml_edit/src/editor.dart:271:14)
#2      main (package:yaml_playground/example.dart:12:14)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by jonasfj** [comment]
Does this also happen if the top-level is not a list?

To be clear, I don't think I have time to dive into all issues that this package might have.
But if you ping me on a PR, or drop me an email `jonasfj@google.com`, I'm happy to help review a PR with appropriate test cases.
